# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI.NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      home_dir: Homeworks/EF/src             
      prj_n: PromoCodeFactory.WebHost
      #prj_test: PromoCodeFactory.UnitTests      

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.home_dir}}/${{ env.prj_n }}/${{ env.prj_n }}.csproj
    - name: Build
      run: dotnet build ${{ env.home_dir}}/${{ env.prj_n }}/${{ env.prj_n }}.csproj  --no-restore
    #- name: Test
    #  run: dotnet test Homeworks/UnitTests/src/${{ env.prj_test }}/${{ env.prj_test }}.csproj --no-build --verbosity normal
